import { useEffect, useState, type FormEvent } from 'react'
import { Archive, Eye, Pencil, Plus, Send, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'

import { announcementService, type AnnouncementCategory, type AnnouncementPriority, type AnnouncementRecord, type AnnouncementStatus, type AnnouncementTarget } from './services'
import './operations-management.css'

type AnnouncementForm = { title: string; message: string; category: AnnouncementCategory; priority: AnnouncementPriority; target: AnnouncementTarget; target_block: string; target_room: string; publish_at: string; expires_at: string }
const emptyForm: AnnouncementForm = { title: '', message: '', category: 'GENERAL', priority: 'NORMAL', target: 'ALL_STUDENTS', target_block: '', target_room: '', publish_at: '', expires_at: '' }
const categories: AnnouncementCategory[] = ['GENERAL', 'ACADEMIC', 'HOSTEL', 'MAINTENANCE', 'MESS', 'SECURITY', 'EVENT', 'EMERGENCY']
const statusTone = (status: AnnouncementStatus) => status === 'PUBLISHED' ? 'mint' : status === 'ARCHIVED' ? 'coral' : 'amber'
const errorMessage = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.'
const localDateTime = (value: string | null) => value ? value.slice(0, 16) : ''

export default function AnnouncementManagement({ mode }: { mode: 'admin' | 'student' }) { return mode === 'admin' ? <AdminAnnouncements /> : <StudentAnnouncements /> }

function AdminAnnouncements() {
  const [records, setRecords] = useState<AnnouncementRecord[]>([]); const [selected, setSelected] = useState<AnnouncementRecord | null>(null); const [editing, setEditing] = useState<AnnouncementRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [statusFilter, setStatusFilter] = useState<AnnouncementStatus | ''>(''); const [categoryFilter, setCategoryFilter] = useState<AnnouncementCategory | ''>(''); const [priorityFilter, setPriorityFilter] = useState<AnnouncementPriority | ''>(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [params, setParams] = useSearchParams()
  const load = async () => { setLoading(true); setError(''); try { setRecords(await announcementService.list()) } catch (requestError) { setError(errorMessage(requestError)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (params.get('create') === '1') { setEditing(null); setFormOpen(true); params.delete('create'); setParams(params, { replace: true }) } }, [params, setParams])
  const visible = records.filter((record) => (!statusFilter || record.status === statusFilter) && (!categoryFilter || record.category === categoryFilter) && (!priorityFilter || record.priority === priorityFilter))
  const openEdit = (record: AnnouncementRecord) => { setEditing(record); setFormOpen(true) }
  const save = async (form: AnnouncementForm) => { setSaving(true); setError(''); const payload = { title: form.title, message: form.message, category: form.category, priority: form.priority, target: form.target, target_block: form.target === 'BLOCK' ? form.target_block : null, target_room: form.target === 'ROOM' ? form.target_room : null, publish_at: form.publish_at ? new Date(form.publish_at).toISOString() : null, expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : null }; try { if (editing) await announcementService.update(editing.id, payload); else await announcementService.create(payload as Omit<AnnouncementRecord, 'id' | 'created_by' | 'created_at' | 'updated_at' | 'status'>); setNotice(editing ? 'Announcement updated.' : 'Announcement draft created.'); setFormOpen(false); await load() } catch (requestError) { setError(errorMessage(requestError)) } finally { setSaving(false) } }
  const transition = async (record: AnnouncementRecord, action: 'publish' | 'archive') => { setSaving(true); setError(''); try { await announcementService[action](record.id); setNotice(`Announcement ${action === 'publish' ? 'published' : 'archived'}.`); await load() } catch (requestError) { setError(errorMessage(requestError)) } finally { setSaving(false) } }
  return <><PageHeader title="Announcements" copy="Create clear, targeted updates for hostel residents." action={<button className="button" type="button" onClick={() => { setEditing(null); setFormOpen(true) }}><Plus size={17} /> New announcement</button>} /><Feedback notice={notice} error={error} clear={() => { setNotice(''); setError('') }} /><section className="panel operations-panel"><div className="operations-toolbar"><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as AnnouncementStatus | '')}><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value as AnnouncementCategory | '')}><option value="">All categories</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select><select value={priorityFilter} onChange={(event) => setPriorityFilter(event.target.value as AnnouncementPriority | '')}><option value="">All priorities</option><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></div>{loading ? <OperationEmpty text="Loading announcements..." /> : visible.length === 0 ? <OperationEmpty text="No announcements match these filters." /> : <div className="announcement-grid">{visible.map((record) => <article className="announcement-admin-card" key={record.id}><div className="announcement-card-top"><span className={`operation-status ${statusTone(record.status)}`}>{record.status}</span><span className="announcement-priority">{record.priority}</span></div><h2>{record.title}</h2><p>{record.message}</p><small>{record.category} · {record.target === 'ALL_STUDENTS' ? 'All students' : record.target === 'BLOCK' ? `Block ${record.target_block}` : `Room ${record.target_room}`}</small><div className="operation-actions"><button className="operation-icon" type="button" onClick={() => setSelected(record)} title="View announcement" aria-label="View announcement"><Eye size={16} /></button>{record.status === 'DRAFT' && <><button className="button compact" type="button" onClick={() => openEdit(record)} disabled={saving}><Pencil size={14} /> Edit</button><button className="button compact mint-button" type="button" onClick={() => void transition(record, 'publish')} disabled={saving}><Send size={14} /> Publish</button></>}{record.status !== 'ARCHIVED' && <button className="button compact coral-button" type="button" onClick={() => void transition(record, 'archive')} disabled={saving}><Archive size={14} /> Archive</button>}</div></article>)}</div>}</section>{selected && <AnnouncementDetail record={selected} close={() => setSelected(null)} />}{formOpen && <AnnouncementForm initial={editing} saving={saving} close={() => !saving && setFormOpen(false)} onSubmit={save} />}</>
}

function StudentAnnouncements() {
  const [records, setRecords] = useState<AnnouncementRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void announcementService.my().then(setRecords).catch((requestError) => setError(errorMessage(requestError))).finally(() => setLoading(false)) }, [])
  return <><PageHeader title="Announcements" copy="Important updates from your hostel team." />{error && <div className="operation-error" role="alert">{error}</div>}{loading ? <OperationEmpty text="Loading announcements..." /> : records.length === 0 ? <OperationEmpty text="No published announcements for you right now." /> : <section className="announcement-grid student-announcement-grid">{records.map((record) => <article className="announcement-admin-card" key={record.id}><div className="announcement-card-top"><span className={`operation-status ${statusTone(record.status)}`}>{record.priority}</span><span>{record.category}</span></div><h2>{record.title}</h2><p>{record.message}</p><small>{record.publish_at ? new Date(record.publish_at).toLocaleString() : 'Published'}</small></article>)}</section>}</>
}

function AnnouncementForm({ initial, saving, close, onSubmit }: { initial: AnnouncementRecord | null; saving: boolean; close: () => void; onSubmit: (form: AnnouncementForm) => Promise<void> }) {
  const [form, setForm] = useState<AnnouncementForm>(initial ? { title: initial.title, message: initial.message, category: initial.category, priority: initial.priority, target: initial.target, target_block: initial.target_block ?? '', target_room: initial.target_room ?? '', publish_at: localDateTime(initial.publish_at), expires_at: localDateTime(initial.expires_at) } : emptyForm)
  const update = (field: keyof AnnouncementForm, value: string) => setForm((previous) => ({ ...previous, [field]: value }))
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); return onSubmit(form) }
  return <div className="modal-backdrop" onMouseDown={close}><div className="modal operations-modal announcement-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">{initial ? 'EDIT DRAFT' : 'NEW ANNOUNCEMENT'}</span><h2>{initial ? 'Edit announcement' : 'Create announcement'}</h2></div><button type="button" onClick={close} aria-label="Close"><X size={18} /></button></div><form className="operations-form" onSubmit={submit}><label>Title<input value={form.title} onChange={(event) => update('title', event.target.value)} required /></label><label>Message<textarea value={form.message} onChange={(event) => update('message', event.target.value)} required /></label><div className="operations-form-grid"><label>Category<select value={form.category} onChange={(event) => update('category', event.target.value)}>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select></label><label>Priority<select value={form.priority} onChange={(event) => update('priority', event.target.value)}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label></div><label>Target<select value={form.target} onChange={(event) => update('target', event.target.value)}><option value="ALL_STUDENTS">All students</option><option value="BLOCK">Block</option><option value="ROOM">Room</option></select></label>{form.target === 'BLOCK' && <label>Target block<input value={form.target_block} onChange={(event) => update('target_block', event.target.value)} placeholder="A" required /></label>}{form.target === 'ROOM' && <label>Target room<input value={form.target_room} onChange={(event) => update('target_room', event.target.value)} placeholder="A-101" required /></label>}<div className="operations-form-grid"><label>Publish at<input type="datetime-local" value={form.publish_at} onChange={(event) => update('publish_at', event.target.value)} /></label><label>Expires at<input type="datetime-local" value={form.expires_at} onChange={(event) => update('expires_at', event.target.value)} /></label></div><button className="button" type="submit" disabled={saving}>{saving ? 'Saving...' : initial ? 'Save draft' : 'Create draft'}</button></form></div></div>
}

function AnnouncementDetail({ record, close }: { record: AnnouncementRecord; close: () => void }) { return <div className="modal-backdrop" onMouseDown={close}><div className="modal operations-modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">ANNOUNCEMENT</span><h2>{record.title}</h2></div><button type="button" onClick={close} aria-label="Close"><X size={18} /></button></div><div className="operation-detail-grid"><span>Status<strong>{record.status}</strong></span><span>Category<strong>{record.category}</strong></span><span>Priority<strong>{record.priority}</strong></span><span>Target<strong>{record.target === 'ALL_STUDENTS' ? 'All students' : record.target === 'BLOCK' ? `Block ${record.target_block}` : `Room ${record.target_room}`}</strong></span><span className="operation-detail-wide">Message<strong>{record.message}</strong></span></div></div></div> }
function PageHeader({ title, copy, action }: { title: string; copy: string; action?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">SMARTSTAY OPERATIONS</span><h1>{title}</h1><p>{copy}</p></div>{action}</div> }
function Feedback({ notice, error, clear }: { notice: string; error: string; clear: () => void }) { return <>{notice && <div className="operation-notice" role="status">{notice}<button type="button" onClick={clear} aria-label="Dismiss"><X size={15} /></button></div>}{error && <div className="operation-error" role="alert">{error}</div>}</> }
function OperationEmpty({ text }: { text: string }) { return <div className="operation-empty">{text}</div> }
